### ISSUE TITLE
What repository is this?

### ISSUE THREAD

**Issue by Dosugamea** [Homarechan/HomarechanBOT#2]
This repository isn't clear now.
It should be more clear to start develop.
What do you make at here?

Joke bot?
Spam bot?
Talk bot with machine learning?
Utility bot for group?
Game bot?

Please give me example of what do you want to make.

**Comment by Homarechan** [comment]
Thank you for your request.

First, It's real that we don't have any objective.
I made this repository inspired at umeneri's suggestion.
We'll start conversation right now and try to make it more clear.
